// Code generated by MockGen. DO NOT EDIT.
// Source: oxide_client.go
//
// Generated by this command:
//
//	mockgen -source=oxide_client.go -destination=oxide_client_mock_test.go -package=oxideauth -mock_names=oxideClient=MockOxideClient
//

// Package oxideauth is a generated GoMock package.
package oxideauth

import (
	context "context"
	reflect "reflect"

	oxide "github.com/oxidecomputer/oxide.go/oxide"
	gomock "go.uber.org/mock/gomock"
)

// MockOxideClient is a mock of oxideClient interface.
type MockOxideClient struct {
	ctrl     *gomock.Controller
	recorder *MockOxideClientMockRecorder
	isgomock struct{}
}

// MockOxideClientMockRecorder is the mock recorder for MockOxideClient.
type MockOxideClientMockRecorder struct {
	mock *MockOxideClient
}

// NewMockOxideClient creates a new mock instance.
func NewMockOxideClient(ctrl *gomock.Controller) *MockOxideClient {
	mock := &MockOxideClient{ctrl: ctrl}
	mock.recorder = &MockOxideClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOxideClient) EXPECT() *MockOxideClientMockRecorder {
	return m.recorder
}

// InstanceView mocks base method.
func (m *MockOxideClient) InstanceView(arg0 context.Context, arg1 oxide.InstanceViewParams) (*oxide.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstanceView", arg0, arg1)
	ret0, _ := ret[0].(*oxide.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InstanceView indicates an expected call of InstanceView.
func (mr *MockOxideClientMockRecorder) InstanceView(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstanceView", reflect.TypeOf((*MockOxideClient)(nil).InstanceView), arg0, arg1)
}

// ProjectView mocks base method.
func (m *MockOxideClient) ProjectView(arg0 context.Context, arg1 oxide.ProjectViewParams) (*oxide.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectView", arg0, arg1)
	ret0, _ := ret[0].(*oxide.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProjectView indicates an expected call of ProjectView.
func (mr *MockOxideClientMockRecorder) ProjectView(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectView", reflect.TypeOf((*MockOxideClient)(nil).ProjectView), arg0, arg1)
}
